org: brandolc18
service: api-s3

provider:
  name: aws
  runtime: python3.13
  region: us-east-1
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::248056481657:role/LabRole
  httpApi:
    cors:
      allowedOrigins:
        - "*"
      allowedHeaders:
        - Content-Type
        - X-Amz-Date
        - Authorization
        - X-Api-Key
        - X-Amz-Security-Token
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS

functions:
  lista_buckets:
    handler: lista_buckets.lambda_handler
    memorySize: 512
    events:
      - httpApi:
          path: /s3/lista-buckets
          method: get

  lista_objetos_bucket:
    handler: lista_objetos_bucket.lambda_handler
    events:
      - httpApi:
          path: /s3/bucket/lista-objetos
          method: post

  crear_bucket_farmacia:
    handler: crear_bucket_farmacia.lambda_handler
    memorySize: 512
    events:
      - httpApi:
          path: /s3/crear-bucket-farmacia
          method: post

  crear_directorio:
    handler: crear_directorio.lambda_handler
    memorySize: 512
    events:
      - httpApi:
          path: /s3/crear-directorio
          method: post

  subir_imagen_farmacia:
    handler: subir_imagen_farmacia.lambda_handler
    memorySize: 1024
    events:
      - httpApi:
          path: /s3/subir-imagen-farmacia
          method: post

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: false
    slim: true
